class CannotFoundObject(Exception):
    pass

class UserAlreadyExists(Exception):
    pass